POST https://bptrust.test/api/t/ValidateToken HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiOWE4YzY5ODRlZjU1MGI0YTMxYWZjMmQwNTA4OGQ2ZWJiODcwOTBkNTJhM2Q1OTc4NmFhYzUzMjZhZGM1NzVlOTQzZTE4Zjc3YjYxNWFkMzQiLCJpYXQiOjE2MzQwOTA1ODgsIm5iZiI6MTYzNDA5MDU4OCwiZXhwIjoxNjY1NjI2NTg4LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.tN1JVGPHe67f_mKzZfApDi3F1X-_iLyQ_Q26qOSj1uMNASAkoXMmvrdjiUP07yHwyw8T9mmkVXgZ4OGUZ8uFV2Cb8rTbWQ4JiT-l27WXfTRwfYb6WqkSpPHlaPe_1cnF7mjQsTJDOaeHu912OWD1nKAVNGHX0KqUM5lU4X6GNo4ON77BalX05l0zgct6H4ZfSSycoZh6B4juy6Z-46LaX033Z7-MSLvphyo07kMeIWggk8HeMCk73y9rOvnelJM4p1-hZqLII5iYuy3VFNvbixugF7Rsf8CD2-V2OS9K-guSk2o7vH3O93IktFujkcZ_DLbS_OxWhVPU9PN5rcO1uPcTko7xfGtEc0hVyaRSTU4irsZZx9-6kAxKWW2lTZ-jaEAa98XY05S126VSuZ71ShqEHVY3Dl2gxZmx3NMQnyn8rXyW9z8rEs_ncdGT1L8LV29OVtIYJ_F4dVFwVrhZVzcZo2kbuAwPRwVzXTI9dqz-p378stFSnejudvv-hX4EaY3G8BRgeCounrD8MoY0BvqR4ylbc1fzGmEMUt1YnpKvO1ZqmQLhTV4WBEjNWUFIGaJYn1To_DPUmUyCPSkm1K9XVcK26nL1W9MqH6UNyWq12EtIcpdKxpEmJIHlgENnMO7UqYRizdbCsJAD_3AqRixrXUzw00Z6IGlGiTpZbOU

{
    "staff_no": "S53788"
} 

