POST https://bptrust.test/api/t/ao/getCurrentCheckins HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiNDFmYTAzMjFiMzQ3NjVkZWY5ZGRiMzI1YTgyMTVkNGVlOWNkMzlhZjlkNTM4NTMwNjk3MDUyYjIyYWZlODE3NWVhOTQxNTBjYTQwOTVkN2MiLCJpYXQiOjE2MzQwNzg5MzgsIm5iZiI6MTYzNDA3ODkzOCwiZXhwIjoxNjY1NjE0OTM4LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.BfwBxruIUn8TGf_1qnskPjlEyle-AF4B1AxlFbNkHB7v-qrJize8-wgqtrSf8jEJH9cECplGCT-OxA4puIbIDmJSEcH1XMiMR4TIfl72XRRW4rbDWWiXaRCouE57T8GyuC85o-qcxPjEq6uxMV98ZhnoBNX0tFstdb0ueEo3jO9jXMqhxdLzgQY7HnSWfQwC-ReLf9Akot8Kl3ksnmjcSAEigOIbOxRe5AxjuZWk8V-0afckw4IvzXdLt4xOHb4jqJcMDu2kj44jN7smvLcR_CZl2EWC3gmSerk_ChN2VNK8hSta7O5AgwCuj92k_N3Imc_qc5s8UI2yN-JTrQ1cOT7SLLJOINA3htvAd7ZbFveoNyKAZaop2REjGWMmImh8-WhYpextNEkcLiqPbhHkUkzsxG4nYHwjiwyDw86XK_e5ojgqaHa8hFmJpflzBfaXdUTYO8klNBBDmNhAJPgeGaCUfwIfodT_346rYsBquu_0rXndtpT7x7QLI0H9gKFxklNLW7OyJMnkH-bgJ_fjxdubDNewXcy0R0ICOEuQURQmFh7WKa7DWKgpk249oOOlTU_idBeAzPN2dvntutoF9-uEjP5zBVquP28q1PTDdQnJUlFHVjr6r9UwYSApsKuuf4s26aL8z6tkz9rlxh-hCaxexN7MVFoypE39MInn0vA

{

} 

