POST https://trustbp.tm.com.my/api/t/ao/getSeatStatus HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIyIiwianRpIjoiNzQ1MDI3MzliYzE4NzA4ODQ3MTg3MTE0Yjc4YzFiMzc5ZTA4ZDljMDhmMjhkZGEyMGI1YTA1MjYzZjdhOWJiOTZjOTZlZTRlMWUxNTgyNGQiLCJpYXQiOjE2MzcwMzM5MDYsIm5iZiI6MTYzNzAzMzkwNiwiZXhwIjoxNjUyNjcyMzA2LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.nIMRyc1Jrv95O6J04I1NCU74hG8AsiiWBBjF1c74sfnpBwktcRHNwMtfP5fSfVmJj6KYPeMW6Uia87K2B4ZlcM_YUcCzBRpc7yaw4Ot78huWy_M7FGXEl_MNm60ESbHOs3dBxMIrP9DGKEsBJvPmjH49FIBu22mRp5cs3rkfn2X-3zakpNSbRNES6ppfWTP6-eW4uxBlSE9tTliNTPXgGnobnrwLfYOi-S7slBhPl2UQPuaEtVrwEGst9skBC-iHtdfdIAImKCnQl7qnEmI4x38_1IOfpTFwSmZxg2AKFA6UbdNUferXHtbv_5qvLTLep7TULm4yTHKeAQSvR9TtxvPlwY8A6ZgIQjrlWnyxB4l7V1Tu3NQy8VBvkXb_2gIt67s-vsayD7XJea9iK_PBk0f2kI94Kjp7w6MEq0hzCTfvsbf3Jy05DnGDBNUnNWWCds4uTJQWdLIB0oVNnQgrFW_9ZhIcZhY0eASdWpn6pmEbBg87Gb1Qtnw5JLG5EhLOu2_Cn-Ao-iV75TdLS4iHq_hrjTttFgkvHlIzMrk13KGUJWtWNT1BSLWdVqRApWlafmoud7UNjMcdRyLTj_kqzukZfX8LqU6Bq1lqLkya6w4lED9X1o_SZfuxb4LEmtUEJ4bzX48s1j0cP9CI-4bXrncUPoMcWt-nkO1CM3xxdhE

{
  "code" : "3b5f0795-0845-4810-9026-9b374d836732"
} 

